# Generated by Django 6.0.3 on 2026-03-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_cart_created_at_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
