# Generated by Django 6.0.3 on 2026-03-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_remove_product_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('delivered', 'Доставлено')], default='in_progress', max_length=32, verbose_name='Статус'),
        ),
    ]
